---
- name: Deployment NGINX
  hosts: test
#  become: yes
#  become_method: sudo
#  become_user: root
  tasks:
      - name: Criando o k8s namespace
        k8s:
          name: teste
          api_version: v1
          kind: Namespace
          state: present