---
- hosts: test
  become: yes
  become_method: sudo
  become_user: root
  vars:
      user: ansible
      itens:
      - qemu-kvm
      - libvirt-daemon-system
      - bridge-utils
      - libguestfs-tools
      - genisoimage
      - virtinst
      - libosinfo-bin
  tasks:
      - name: Instalação de pré-requisitos minikube
        apt:
            name: "{{ itens }}"
            state: latest      
      
      - name: Download da imagem do Minikube
        get_url: 
          url: 'https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb'
          dest: '/opt'
      
      - name: Descompactar e Instalar o Minikube
        command: dpkg -i /opt/minikube_latest_amd64.deb

      - name: Download do Kubectl
        command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      
      - name: Permissão de executar ao Kubectl
        command: chmod +x /usr/bin/kubectl      
      
      - name: Adicionar usuário ao Libvirt
        command: adduser "{{ user }}" libvirt